version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d/
      - ./data/keys:/etc/nginx/keys/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web
  web:
    image: akalay27/codingcamp2021:latest
    ports:
      - "5432:5432"
    expose:
      - "4000"